// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class DefaultsParameters
{
    /** Missing requests SQL DEFAULT; explicit null is a supplied value. SQL Server validates required inputs. */
    declare "first"?: number | null;
    /** Missing requests SQL DEFAULT; explicit null is a supplied value. SQL Server validates required inputs. */
    declare "middle"?: string | null;
    /** Missing requests SQL DEFAULT; explicit null is a supplied value. SQL Server validates required inputs. */
    declare "last"?: number;
}
