// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class DoWorkParameters
{
    /** Missing requests SQL DEFAULT; explicit null is a supplied value. SQL Server validates required inputs. */
    declare "class"?: string | null;
    /** Assign an initial value or null explicitly to capture INPUT/OUTPUT. */
    declare "cancellationToken": number | null;
    /** Assign an initial value or null explicitly to capture INPUT/OUTPUT. */
    declare "p0": string | null;
}
