// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class DoWorkOutput
{
    declare "cancellationToken": number | null;
    declare "p0": string | null;
}
