// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class EchoParameters2
{
    /** Missing requests SQL DEFAULT; explicit null is a supplied value. SQL Server validates required inputs. */
    declare "filter"?: string | null;
}
