// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class OnlyLongParameters
{
    /** Missing requests SQL DEFAULT; explicit null is a supplied value. SQL Server validates required inputs. */
    /** JSON number: integers outside JavaScript's safe integer range can lose precision. Use a string-valued API DTO for exact large IDs. */
    declare "value"?: number;
}
