// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class ReadRowsParameters
{
    /** Assign an initial value or null explicitly to capture INPUT/OUTPUT. */
    declare "count": number | null;
}
