"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DboAB = void 0;
class DboAB {
}
exports.DboAB = DboAB;
