"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DboAB2 = void 0;
class DboAB2 {
}
exports.DboAB2 = DboAB2;
