"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.QuotedTable = void 0;
class QuotedTable {
}
exports.QuotedTable = QuotedTable;
