using SqlModelGenerator.Metadata;
using SqlModelGenerator.Metadata.Models;
using static SqlModelGenerator.Metadata.NameHelper;

namespace SqlModelGenerator.Generators;

public sealed class DbContextGenerator
{
    private readonly CodeGeneratorOptions _options;
    public DbContextGenerator(CodeGeneratorOptions options) => _options = options;
    private string Type(string folder, string name) => $"global::{_options.RootNamespace}.{folder}.{name}";
    private static string Properties(DbTableInfo table, IEnumerable<string> names)
    {
        var props = names.Select(n => "e." + table.Columns.Single(c => c.Name == n).PropertyName).ToArray();
        return props.Length == 1 ? props[0] : "new { " + string.Join(", ", props) + " }";
    }

    public void Generate(DatabaseModel model)
    {
        Directory.CreateDirectory(_options.OutputRoot);
        var w = new CodeWriter();
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine("using Microsoft.EntityFrameworkCore;");
        w.WriteLine($"namespace {_options.RootNamespace};");
        w.WriteLine();
        w.WriteLine($"public partial class {_options.DbContextName} : DbContext");
        w.OpenBlock();
        w.WriteLine($"public {_options.DbContextName}(DbContextOptions<{_options.DbContextName}> options) : base(options) {{ }}");
        foreach (var t in model.Tables) w.WriteLine($"public DbSet<{Type("Entities", t.ClassName)}> {t.SetName} => Set<{Type("Entities", t.ClassName)}>();");
        foreach (var v in model.Views) w.WriteLine($"public DbSet<{Type("Views", v.ClassName)}> {v.SetName} => Set<{Type("Views", v.ClassName)}>();");
        foreach (var p in model.Procedures.Where(p => p.HasResultSet && p.GenerationError == null))
            w.WriteLine($"public DbSet<{Type("Procedures", p.ResultClassName)}> {p.SetName} => Set<{Type("Procedures", p.ResultClassName)}>();");
        w.WriteLine();
        w.WriteLine("protected override void OnModelCreating(ModelBuilder modelBuilder)");
        w.OpenBlock();
        foreach (var t in model.Tables)
        {
            w.WriteLine($"modelBuilder.Entity<{Type("Entities", t.ClassName)}>(entity =>");
            w.OpenBlock();
            w.WriteLine($"entity.ToTable({Literal(t.Name)}, {Literal(t.Schema)});");
            w.WriteLine(t.PrimaryKeyColumns.Count == 0 ? "entity.HasNoKey();" : $"entity.HasKey(e => {Properties(t, t.PrimaryKeyColumns)});");
            foreach (var c in t.Columns) WriteColumn(w, c, true);
            foreach (var fk in t.OutgoingForeignKeys)
            {
                var principal = fk.PrincipalTable;
                var dependentType = Type("Entities", t.ClassName);
                var principalType = Type("Entities", principal.ClassName);
                var chain = $"entity.HasOne(e => e.{fk.DependentNavigation})";
                chain += fk.IsUnique ? $".WithOne(e => e.{fk.PrincipalNavigation})" : $".WithMany(e => e.{fk.PrincipalNavigation})";
                chain += $".HasForeignKey{(fk.IsUnique ? "<" + dependentType + ">" : "")}(e => {Properties(t, fk.Columns.Select(c => c.DependentColumn))})";
                chain += $".HasPrincipalKey{(fk.IsUnique ? "<" + principalType + ">" : "")}(e => {Properties(principal, fk.Columns.Select(c => c.PrincipalColumn))})";
                var delete = fk.DeleteAction switch { "CASCADE" => "Cascade", "SET_NULL" => "SetNull", _ => "NoAction" };
                chain += $".IsRequired({(fk.IsRequired ? "true" : "false")}).OnDelete(DeleteBehavior.{delete}).HasConstraintName({Literal(fk.Name)});";
                w.WriteLine(chain);
            }
            w.CloseBlock(");");
        }
        foreach (var v in model.Views)
        {
            w.WriteLine($"modelBuilder.Entity<{Type("Views", v.ClassName)}>(entity =>");
            w.OpenBlock();
            w.WriteLine($"entity.HasNoKey().ToView({Literal(v.Name)}, {Literal(v.Schema)});");
            foreach (var c in v.Columns) WriteColumn(w, c, false);
            w.CloseBlock(");");
        }
        foreach (var p in model.Procedures.Where(p => p.HasResultSet && p.GenerationError == null))
        {
            w.WriteLine($"modelBuilder.Entity<{Type("Procedures", p.ResultClassName)}>(entity =>");
            w.OpenBlock();
            w.WriteLine("entity.HasNoKey().ToView((string?)null);");
            foreach (var c in p.ResultColumns)
                w.WriteLine($"entity.Property(e => e.{c.PropertyName}).HasColumnName({Literal(c.Name)}).IsRequired({(!c.IsNullable ? "true" : "false")});");
            w.CloseBlock(");");
        }
        w.WriteLine("base.OnModelCreating(modelBuilder);");
        w.CloseBlock();
        w.CloseBlock();
        File.WriteAllText(Path.Combine(_options.OutputRoot, _options.DbContextName + ".g.cs"), w.ToString());
    }

    private static void WriteColumn(CodeWriter w, DbColumnInfo c, bool table)
    {
        var type = c.SqlTypeName.ToLowerInvariant();
        var storeType = type;
        if (type is "nvarchar" or "nchar" or "varchar" or "char" or "varbinary" or "binary")
        {
            if (c.MaxLength is int length)
            {
                var size = length == -1 ? "max" : ((type is "nvarchar" or "nchar") ? length / 2 : length).ToString(System.Globalization.CultureInfo.InvariantCulture);
                storeType += "(" + size + ")";
            }
        }
        else if (type is "decimal" or "numeric") storeType += $"({c.Precision ?? 18},{c.Scale ?? 0})";
        else if (type is "time" or "datetime2" or "datetimeoffset") storeType += $"({c.Scale ?? 7})";
        var chain = $"entity.Property(e => e.{c.PropertyName}).HasColumnName({Literal(c.Name)}).HasColumnType({Literal(storeType)}).IsRequired({(!c.IsNullable ? "true" : "false")})";
        if (table)
        {
            if (type is "timestamp" or "rowversion") chain += ".IsRowVersion()";
            else if (c.IsComputed) chain += c.ComputedSql != null ? $".HasComputedColumnSql({Literal(c.ComputedSql)}, stored: {(c.IsStored ? "true" : "false")})" : ".ValueGeneratedOnAddOrUpdate()";
            else if (c.IsIdentity) chain += ".UseIdentityColumn()";
            else if (c.DefaultSql != null) chain += $".HasDefaultValueSql({Literal(c.DefaultSql)})";
            else chain += ".ValueGeneratedNever()";
        }
        w.WriteLine(chain + ";");
    }
}
