using System.Text.Json;

namespace SqlModelGenerator.Generators;

// Owns only this run's staging directory and source files identified by its format-specific manifest.
internal sealed class GeneratedOutput : IDisposable
{
    private readonly string _root;
    private readonly string _manifest;
    private readonly string _extension;
    private string[]? _files;
    private string[] _previous = [];
    public string Staging { get; }

    public GeneratedOutput(string root, string manifestName, string extension)
    {
        _root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(root));
        _manifest = Path.Combine(_root, manifestName);
        _extension = extension;
        Directory.CreateDirectory(_root);
        Staging = Path.Combine(_root, ".sqlmodel-staging-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Staging);
    }

    public void ValidatePublication()
    {
        _files = Directory.GetFiles(Staging, "*", SearchOption.AllDirectories)
            .Select(f => Path.GetRelativePath(Staging, f)).Order(StringComparer.Ordinal).ToArray();
        _previous = File.Exists(_manifest) ? JsonSerializer.Deserialize<string[]>(File.ReadAllText(_manifest)) ?? [] : [];
        foreach (var relative in _previous) _ = ChildPath(relative);
        foreach (var relative in _files)
        {
            var target = ChildPath(relative);
            if (File.Exists(target) && IsSource(relative) && !IsGenerated(target))
                throw new IOException($"Output file is not owned by this generator: {target}. Choose a fresh output folder.");
        }
    }

    public void Publish()
    {
        if (_files == null) throw new InvalidOperationException("Validate output before publishing.");
        foreach (var relative in _files)
        {
            var target = ChildPath(relative);
            Directory.CreateDirectory(Path.GetDirectoryName(target)!);
            File.Copy(Path.Combine(Staging, relative), target, overwrite: true);
        }
        foreach (var relative in _previous.Except(_files, StringComparer.OrdinalIgnoreCase))
        {
            var stale = ChildPath(relative);
            if (File.Exists(stale) && IsSource(relative) && IsGenerated(stale)) File.Delete(stale);
        }
        File.WriteAllText(_manifest, JsonSerializer.Serialize(_files, new JsonSerializerOptions { WriteIndented = true }));
    }

    private bool IsSource(string relative) => relative.EndsWith(_extension, StringComparison.OrdinalIgnoreCase);
    private static bool IsGenerated(string file) => File.ReadAllText(file).StartsWith("// <auto-generated />", StringComparison.Ordinal);
    private string ChildPath(string relative)
    {
        var full = Path.GetFullPath(Path.Combine(_root, relative));
        if (!full.StartsWith(Path.TrimEndingDirectorySeparator(_root) + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            throw new IOException("Generated-file manifest contains a path outside the output directory.");
        return full;
    }
    public void Dispose()
    {
        // Never recursively delete any path other than this object's newly allocated direct child.
        if (Path.GetDirectoryName(Path.GetFullPath(Staging)) == _root) Directory.Delete(Staging, recursive: true);
    }
}
