using System.Text.Json;
using SqlModelGenerator.Metadata;
using SqlModelGenerator.Metadata.Models;

namespace SqlModelGenerator.Generators;

public static class ModelGenerator
{
    // Generate everything before replacing output; a metadata/code-generation failure keeps old output intact.
    public static void Generate(DatabaseModel model, CodeGeneratorOptions options)
    {
        ModelPreparation.Prepare(model, options.DbContextName);
        var root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(options.OutputRoot));
        Directory.CreateDirectory(root);
        var staging = Path.Combine(root, ".sqlmodel-staging-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(staging);
        try
        {
            var staged = options with { OutputRoot = staging };
            var poco = new PocoGenerator(staged);
            poco.GenerateTables(model.Tables);
            poco.GenerateViews(model.Views);
            new ProcedureGenerator(staged).Generate(model.Procedures);
            new DbContextGenerator(staged).Generate(model);
            new ReportGenerator(staged).Generate(model);
            var files = Directory.GetFiles(staging, "*", SearchOption.AllDirectories).Select(f => Path.GetRelativePath(staging, f)).Order().ToArray();
            var manifest = Path.Combine(root, ".sqlmodel-files.json");
            var previous = File.Exists(manifest) ? JsonSerializer.Deserialize<string[]>(File.ReadAllText(manifest)) ?? [] : [];
            foreach (var relative in files)
            {
                var target = ChildPath(root, relative);
                // Permit replacement of files this generator already owns, but preserve hand-written files.
                if (File.Exists(target) && relative.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
                    && !File.ReadAllText(target).StartsWith("// <auto-generated />", StringComparison.Ordinal))
                    throw new IOException($"Output file is not owned by this generator: {target}. Choose a fresh output folder.");
            }
            foreach (var relative in files)
            {
                var target = ChildPath(root, relative);
                Directory.CreateDirectory(Path.GetDirectoryName(target)!);
                File.Copy(Path.Combine(staging, relative), target, overwrite: true);
            }
            foreach (var relative in previous.Except(files, StringComparer.OrdinalIgnoreCase))
            {
                var stale = ChildPath(root, relative);
                if (File.Exists(stale) && relative.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)
                    && File.ReadAllText(stale).StartsWith("// <auto-generated />", StringComparison.Ordinal)) File.Delete(stale);
            }
            File.WriteAllText(manifest, JsonSerializer.Serialize(files, new JsonSerializerOptions { WriteIndented = true }));
        }
        finally
        {
            // This freshly allocated directory is always a direct child of the requested output root.
            if (Path.GetDirectoryName(Path.GetFullPath(staging)) == root) Directory.Delete(staging, recursive: true);
        }
    }

    private static string ChildPath(string root, string relative)
    {
        var full = Path.GetFullPath(Path.Combine(root, relative));
        if (!full.StartsWith(Path.TrimEndingDirectorySeparator(root) + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            throw new IOException("Generated-file manifest contains a path outside the output directory.");
        return full;
    }
}
