using SqlModelGenerator.Metadata.Models;

namespace SqlModelGenerator.Generators;

public sealed class PocoGenerator
{
    private readonly CodeGeneratorOptions _options;
    public PocoGenerator(CodeGeneratorOptions options) => _options = options;
    public void GenerateTables(IEnumerable<DbTableInfo> tables)
    {
        foreach (var table in tables) Generate(table, "Entities");
    }
    public void GenerateViews(IEnumerable<DbViewInfo> views)
    {
        foreach (var view in views) Generate(view, "Views");
    }
    public static string Initializer(string type) => type is "string" or "byte[]" or "object" ? " = null!;" : "";

    private void Generate(DbObjectBase obj, string folder)
    {
        var dir = Path.Combine(_options.OutputRoot, folder);
        Directory.CreateDirectory(dir);
        var w = new CodeWriter();
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine($"namespace {_options.RootNamespace}.{folder};");
        w.WriteLine();
        w.WriteLine($"public partial class {obj.ClassName}");
        w.OpenBlock();
        foreach (var c in obj.Columns.OrderBy(x => x.Ordinal))
            w.WriteLine($"public {c.ClrTypeName} {c.PropertyName} {{ get; set; }}{Initializer(c.ClrTypeName)}");
        if (obj is DbTableInfo table)
        {
            foreach (var fk in table.OutgoingForeignKeys)
            {
                var type = fk.PrincipalTable.ClassName;
                w.WriteLine($"public {type}{(fk.IsRequired ? "" : "?")} {fk.DependentNavigation} {{ get; set; }}{(fk.IsRequired ? " = null!;" : "")}");
            }
            foreach (var fk in table.IncomingForeignKeys)
            {
                var type = fk.DependentTable.ClassName;
                if (fk.IsUnique) w.WriteLine($"public {type}? {fk.PrincipalNavigation} {{ get; set; }}");
                else w.WriteLine($"public global::System.Collections.Generic.ICollection<{type}> {fk.PrincipalNavigation} {{ get; set; }} = new global::System.Collections.Generic.List<{type}>();");
            }
        }
        w.CloseBlock();
        File.WriteAllText(Path.Combine(dir, obj.ClassName.TrimStart('@') + ".cs"), w.ToString());
    }
}
