using SqlModelGenerator.Metadata;
using SqlModelGenerator.Metadata.Models;

namespace SqlModelGenerator.Generators;

public sealed class ProcedureContractsGenerator
{
    private readonly CodeGeneratorOptions _options;
    public ProcedureContractsGenerator(CodeGeneratorOptions options) => _options = options;
    public static string InputType(DbParameterInfo p) => p.IsOutput ? SqlTypeMapper.ToClrType(p.SqlTypeName, true) : p.ClrTypeName;
    public static string OutputType(DbParameterInfo p) => SqlTypeMapper.ToClrType(p.SqlTypeName, true);

    public void Generate(IReadOnlyList<DbProcedureInfo> procedures)
    {
        var supported = procedures.Where(p => p.ParametersComplete).ToList();
        if (supported.Count == 0) return;
        var directory = Path.Combine(_options.OutputRoot, "Procedures");
        Directory.CreateDirectory(directory);
        foreach (var proc in supported)
        {
            var w = Begin(proc.ParametersClassName);
            foreach (var p in proc.Parameters.OrderBy(p => p.Ordinal))
            {
                w.WriteLine(p.IsOutput
                    ? "// Assign an initial value (or null) explicitly to capture this INPUT/OUTPUT parameter."
                    : "// Unspecified requests SQL DEFAULT; assigning null explicitly sends SQL NULL.");
                w.WriteLine("[global::System.Text.Json.Serialization.JsonIgnore(Condition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]");
                w.WriteLine($"public global::{_options.RootNamespace}.ProcedureSupport.ProcedureArgument<{InputType(p)}> {p.PropertyName} {{ get; set; }}");
            }
            w.CloseBlock();
            File.WriteAllText(Path.Combine(directory, proc.ParametersClassName + ".cs"), w.ToString());
            if (proc.Parameters.Any(p => p.IsOutput))
            {
                w = Begin(proc.OutputClassName);
                foreach (var p in proc.Parameters.Where(p => p.IsOutput).OrderBy(p => p.Ordinal))
                    w.WriteLine($"public {OutputType(p)} {p.PropertyName} {{ get; set; }}");
                w.CloseBlock();
                File.WriteAllText(Path.Combine(directory, proc.OutputClassName + ".cs"), w.ToString());
            }
        }
        var support = Path.Combine(_options.OutputRoot, "ProcedureSupport");
        Directory.CreateDirectory(support);
        File.WriteAllText(Path.Combine(support, "ProcedureArgument.cs"), SupportSource.Replace("__NAMESPACE__", _options.RootNamespace));
    }

    private CodeWriter Begin(string name)
    {
        var w = new CodeWriter();
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        w.WriteLine($"namespace {_options.RootNamespace}.Procedures;");
        w.WriteLine($"public partial class {name}");
        w.OpenBlock();
        return w;
    }

    private const string SupportSource = """
        // <auto-generated />
        #nullable enable
        namespace __NAMESPACE__.ProcedureSupport;

        /// <summary>Tracks whether an argument was supplied, independently of its value (including null).</summary>
        [global::System.Text.Json.Serialization.JsonConverter(typeof(ProcedureArgumentJsonConverterFactory))]
        public readonly struct ProcedureArgument<T>
        {
            private readonly T _value;
            public bool IsSpecified { get; }
            public T GetValue() => IsSpecified ? _value : throw new global::System.InvalidOperationException("The procedure argument was not supplied.");
            public ProcedureArgument(T value) { _value = value; IsSpecified = true; }
            public static implicit operator ProcedureArgument<T>(T value) => new(value);
        }

        // The public JSON shape remains a plain value: { "customerId": 42 }, never { "isSpecified": ... }.
        public sealed class ProcedureArgumentJsonConverterFactory : global::System.Text.Json.Serialization.JsonConverterFactory
        {
            public override bool CanConvert(global::System.Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(ProcedureArgument<>);
            public override global::System.Text.Json.Serialization.JsonConverter CreateConverter(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
            {
                var converter = typeof(ArgumentConverter<>).MakeGenericType(type.GetGenericArguments());
                return (global::System.Text.Json.Serialization.JsonConverter)global::System.Activator.CreateInstance(converter)!;
            }
            private sealed class ArgumentConverter<T> : global::System.Text.Json.Serialization.JsonConverter<ProcedureArgument<T>>
            {
                public ArgumentConverter() { }
                public override bool HandleNull => true;
                public override ProcedureArgument<T> Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
                    => new(global::System.Text.Json.JsonSerializer.Deserialize<T>(ref reader, options)!);
                public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ProcedureArgument<T> value, global::System.Text.Json.JsonSerializerOptions options)
                    => global::System.Text.Json.JsonSerializer.Serialize(writer, value.GetValue(), options);
            }
        }
        """;
}
