using SqlModelGenerator.Metadata;
using SqlModelGenerator.Metadata.Models;
using static SqlModelGenerator.Metadata.NameHelper;

namespace SqlModelGenerator.Generators;

public sealed class ProcedureGenerator
{
    private readonly CodeGeneratorOptions _options;
    public ProcedureGenerator(CodeGeneratorOptions options) => _options = options;

    public void Generate(IEnumerable<DbProcedureInfo> procedures)
    {
        var list = procedures.OrderBy(p => p.Schema, StringComparer.Ordinal).ThenBy(p => p.Name, StringComparer.Ordinal).ToList();
        var dir = Path.Combine(_options.OutputRoot, "Procedures");
        Directory.CreateDirectory(dir);
        foreach (var p in list.Where(p => p.HasResultSet && p.GenerationError == null))
        {
            var code = new CodeWriter();
            code.WriteLine("// <auto-generated />");
            code.WriteLine("#nullable enable");
            code.WriteLine($"namespace {_options.RootNamespace}.Procedures;");
            code.WriteLine($"public partial class {p.ResultClassName}");
            code.OpenBlock();
            foreach (var c in p.ResultColumns.OrderBy(c => c.Ordinal))
                code.WriteLine($"public {c.ClrTypeName} {c.PropertyName} {{ get; set; }}{PocoGenerator.Initializer(c.ClrTypeName)}");
            code.CloseBlock();
            File.WriteAllText(Path.Combine(dir, p.ResultClassName + ".cs"), code.ToString());
        }
        var w = new CodeWriter();
        w.WriteLine("// <auto-generated />");
        w.WriteLine("#nullable enable");
        foreach (var ns in new[] { "System", "System.Data", "System.Collections.Generic", "System.Threading", "System.Threading.Tasks", "Microsoft.Data.SqlClient", "Microsoft.EntityFrameworkCore" }) w.WriteLine($"using {ns};");
        w.WriteLine($"namespace {_options.RootNamespace};");
        w.WriteLine($"public partial class {_options.DbContextName}");
        w.OpenBlock();
        foreach (var p in list) WriteMethod(w, p);
        w.CloseBlock();
        File.WriteAllText(Path.Combine(dir, _options.DbContextName + ".Procedures.g.cs"), w.ToString());
    }

    public static string CommandText(DbProcedureInfo p)
    {
        var args = p.Parameters.OrderBy(x => x.Ordinal).Select((x, i) => $"@__arg{i}" + (x.IsOutput ? " OUTPUT" : ""));
        return $"EXEC {SqlIdentifier(p.Schema)}.{SqlIdentifier(p.Name)}" + (p.Parameters.Count == 0 ? "" : " " + string.Join(", ", args));
    }

    public static int? ParameterSize(DbParameterInfo p)
    {
        if (p.SqlTypeName.ToLowerInvariant() is not ("nvarchar" or "nchar" or "varchar" or "char" or "varbinary" or "binary" or "image" or "text" or "ntext")) return null;
        if (p.SqlTypeName.ToLowerInvariant() is "image" or "text" or "ntext") return -1;
        if (p.MaxLength is not int size || size == 0) return null;
        return size > 0 && p.SqlTypeName.ToLowerInvariant() is "nvarchar" or "nchar" ? size / 2 : size;
    }

    private void WriteMethod(CodeWriter w, DbProcedureInfo proc)
    {
        var parameters = proc.Parameters.OrderBy(p => p.Ordinal).ToList();
        var signature = parameters.Select(p => $"{p.ClrTypeName} {p.VariableName}").ToList();
        signature.Add("CancellationToken cancellationToken = default");
        if (parameters.Any(p => p.IsOutput)) signature.Add("IDictionary<string, object?>? outputValues = null");
        var resultType = $"global::{_options.RootNamespace}.Procedures.{proc.ResultClassName}";
        var returnType = proc.HasResultSet && proc.GenerationError == null ? $"Task<List<{resultType}>>" : "Task<int>";
        w.WriteLine($"public {(proc.GenerationError == null ? "async " : "")}{returnType} {proc.MethodName}Async({string.Join(", ", signature)})");
        w.OpenBlock();
        if (proc.GenerationError != null)
        {
            w.WriteLine($"throw new NotSupportedException({Literal("Procedure metadata is incomplete: " + proc.GenerationError)});");
            w.CloseBlock();
            return;
        }
        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            w.WriteLine($"var p{i} = new SqlParameter({Literal("@__arg" + i)}, {SqlTypeMapper.ToSqlDbTypeExpression(p.SqlTypeName)})");
            w.OpenBlock();
            w.WriteLine($"Value = (object?){p.VariableName} ?? DBNull.Value,");
            w.WriteLine($"Direction = ParameterDirection.{(p.IsOutput ? "InputOutput" : "Input")}");
            w.CloseBlock(";");
            if (ParameterSize(p) is int size) w.WriteLine($"p{i}.Size = {size};");
            if (p.Precision is > 0) w.WriteLine($"p{i}.Precision = {p.Precision};");
            if (p.Scale is byte scale) w.WriteLine($"p{i}.Scale = {scale};");
        }
        w.WriteLine("object[] sqlParameters = new object[] { " + string.Join(", ", parameters.Select((p, i) => "p" + i)) + " };");
        // EF's Raw methods use composite formatting even when every argument is a DbParameter.
        var sql = Literal(CommandText(proc).Replace("{", "{{").Replace("}", "}}"));
        if (proc.HasResultSet)
            w.WriteLine($"var result = await Set<{resultType}>().FromSqlRaw({sql}, sqlParameters).AsNoTracking().ToListAsync(cancellationToken);");
        else w.WriteLine($"var result = await Database.ExecuteSqlRawAsync({sql}, sqlParameters, cancellationToken);");
        for (var i = 0; i < parameters.Count; i++)
            if (parameters[i].IsOutput) w.WriteLine($"if (outputValues != null) outputValues[{Literal(parameters[i].ParameterName)}] = p{i}.Value is DBNull ? null : p{i}.Value;");
        w.WriteLine("return result;");
        w.CloseBlock();
    }
}
