using System.Text.Json;
using SqlModelGenerator.Metadata;
using SqlModelGenerator.Metadata.Models;

namespace SqlModelGenerator.Generators;

public sealed class TypeScriptGenerator
{
    public static string JsonPropertyName(string csharpName) => JsonNamingPolicy.CamelCase.ConvertName(csharpName.TrimStart('@'));

    public void Generate(DatabaseModel model, string outputFolder)
    {
        Directory.CreateDirectory(outputFolder);
        var exports = new List<string>();
        foreach (var table in model.Tables)
        {
            var related = table.OutgoingForeignKeys.Select(f => f.PrincipalTable)
                .Concat(table.IncomingForeignKeys.Select(f => f.DependentTable))
                .Where(t => t != table).Select(t => t.ClassName).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal);
            var w = Begin(table.ClassName, related);
            foreach (var c in table.Columns.OrderBy(c => c.Ordinal)) WriteColumn(w, c.PropertyName, c.SqlTypeName, c.IsNullable);
            foreach (var fk in table.OutgoingForeignKeys)
                WriteNavigation(w, fk.DependentNavigation, fk.PrincipalTable.ClassName);
            foreach (var fk in table.IncomingForeignKeys)
                WriteNavigation(w, fk.PrincipalNavigation, fk.DependentTable.ClassName + (fk.IsUnique ? "" : "[]"));
            w.CloseBlock();
            Save(outputFolder, "entities", table.ClassName, w, exports);
        }
        foreach (var view in model.Views)
        {
            var w = Begin(view.ClassName, []);
            foreach (var c in view.Columns.OrderBy(c => c.Ordinal)) WriteColumn(w, c.PropertyName, c.SqlTypeName, c.IsNullable);
            w.CloseBlock();
            Save(outputFolder, "views", view.ClassName, w, exports);
        }
        foreach (var proc in model.Procedures.Where(p => p.HasResultSet && p.GenerationError == null))
        {
            var w = Begin(proc.ResultClassName, []);
            foreach (var c in proc.ResultColumns.OrderBy(c => c.Ordinal)) WriteColumn(w, c.PropertyName, c.SqlTypeName, c.IsNullable);
            w.CloseBlock();
            Save(outputFolder, "procedures", proc.ResultClassName, w, exports);
        }
        foreach (var proc in model.Procedures.Where(p => p.ParametersComplete))
        {
            var w = Begin(proc.ParametersClassName, []);
            foreach (var p in proc.Parameters.OrderBy(p => p.Ordinal))
            {
                w.WriteLine(p.IsOutput
                    ? "/** Assign an initial value or null explicitly to capture INPUT/OUTPUT. */"
                    : "/** Missing requests SQL DEFAULT; explicit null is a supplied value. SQL Server validates required inputs. */");
                if (TypeScriptTypeMapper.Note(p.SqlTypeName) is string note) w.WriteLine("/** " + note + " */");
                w.WriteLine($"declare {Property(p.PropertyName)}{(p.IsOutput ? "" : "?")}: {TypeScriptTypeMapper.ToType(p.SqlTypeName, p.IsNullable || p.IsOutput)};");
            }
            w.CloseBlock();
            Save(outputFolder, "procedures", proc.ParametersClassName, w, exports);
            if (proc.Parameters.Any(p => p.IsOutput))
            {
                w = Begin(proc.OutputClassName, []);
                foreach (var p in proc.Parameters.Where(p => p.IsOutput).OrderBy(p => p.Ordinal))
                    WriteColumn(w, p.PropertyName, p.SqlTypeName, true);
                w.CloseBlock();
                Save(outputFolder, "procedures", proc.OutputClassName, w, exports);
            }
        }
        var index = new CodeWriter();
        index.WriteLine("// <auto-generated />");
        foreach (var export in exports.Order(StringComparer.Ordinal)) index.WriteLine(export);
        if (exports.Count == 0) index.WriteLine("export {};");
        File.WriteAllText(Path.Combine(outputFolder, "index.ts"), index.ToString());
    }

    private static CodeWriter Begin(string name, IEnumerable<string> related)
    {
        var w = new CodeWriter();
        w.WriteLine("// <auto-generated />");
        w.WriteLine("// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.");
        foreach (var type in related) w.WriteLine($"import type {{ {type} }} from {NameHelper.Literal("./" + type)};");
        w.WriteLine();
        w.WriteLine($"export class {name}");
        w.OpenBlock();
        return w;
    }

    private static string Property(string name)
    {
        var jsonName = JsonPropertyName(name);
        // Computed syntax keeps a valid JSON property named 'constructor' from becoming a TS constructor.
        return jsonName == "constructor" ? "[\"constructor\"]" : NameHelper.Literal(jsonName);
    }

    private static void WriteColumn(CodeWriter w, string name, string sqlType, bool nullable)
    {
        if (TypeScriptTypeMapper.Note(sqlType) is string note) w.WriteLine("/** " + note + " */");
        w.WriteLine($"declare {Property(name)}: {TypeScriptTypeMapper.ToType(sqlType, nullable)};");
    }

    private static void WriteNavigation(CodeWriter w, string name, string type)
    {
        w.WriteLine("/** Optional: the API may omit unloaded or ignored navigation properties. */");
        w.WriteLine($"declare {Property(name)}?: {type} | null;");
    }

    private static void Save(string root, string folder, string name, CodeWriter writer, List<string> exports)
    {
        var directory = Path.Combine(root, folder);
        Directory.CreateDirectory(directory);
        File.WriteAllText(Path.Combine(directory, name + ".ts"), writer.ToString());
        exports.Add($"export {{ {name} }} from {NameHelper.Literal("./" + folder + "/" + name)};");
    }
}
