"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ABParameters = void 0;
class ABParameters {
}
exports.ABParameters = ABParameters;
