"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.DoWorkParameters = void 0;
class DoWorkParameters {
}
exports.DoWorkParameters = DoWorkParameters;
