"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.EchoParameters2 = void 0;
class EchoParameters2 {
}
exports.EchoParameters2 = EchoParameters2;
