"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReadRowsParameters = void 0;
class ReadRowsParameters {
}
exports.ReadRowsParameters = ReadRowsParameters;
