"use strict";
// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
Object.defineProperty(exports, "__esModule", { value: true });
exports.UnknownParameters = void 0;
class UnknownParameters {
}
exports.UnknownParameters = UnknownParameters;
