// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
import type { Composite } from "./Composite";

export class CompositeChild
{
    declare "id": number;
    declare "a": number;
    declare "b": number;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "composite"?: Composite | null;
}
