// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
import type { CompositeChild } from "./CompositeChild";

export class Composite
{
    declare "a": number;
    declare "b": number;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "compositeChildsViaComposite"?: CompositeChild[] | null;
}
