// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
import type { CodeUse } from "./CodeUse";
import type { Legacy } from "./Legacy";
import type { Order } from "./Order";
import type { Profile } from "./Profile";

export class Customer
{
    declare "id": number;
    declare "code": string;
    declare "name": string;
    declare "managerId": number | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "manager"?: Customer | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "codeUsesViaCustomer"?: CodeUse[] | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "legacysViaCustomer"?: Legacy[] | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "customersViaManager"?: Customer[] | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "ordersViaCustomer"?: Order[] | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "ordersViaReviewer"?: Order[] | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "profileViaCustomer"?: Profile | null;
}
