// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
import type { Customer } from "./Customer";

export class Legacy
{
    declare "id": number;
    declare "customerId": number;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "customer"?: Customer | null;
}
