// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.
import type { Customer } from "./Customer";

export class Order
{
    declare "id": number;
    declare "customerId": number;
    declare "reviewerId": number | null;
    /** JSON number: JavaScript cannot represent all decimal values exactly. Use a string-valued API DTO when exact decimal precision is required. */
    declare "amount": number;
    /** Base64-encoded JSON string (System.Text.Json byte[] representation). */
    declare "version": string;
    declare "defaulted": number;
    declare "computed": number;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "customer"?: Customer | null;
    /** Optional: the API may omit unloaded or ignored navigation properties. */
    declare "reviewer"?: Customer | null;
}
