// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class QuotedTable
{
    declare "id": number;
    declare "quotedTable2": number;
    declare "ab": string;
    declare "aB2": string;
    declare "twoQuotes": string;
}
