// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class SaveChange
{
    declare "id": number;
    declare "getType2": number;
    declare "toString2": number;
    declare "equals2": number;
}
