// <auto-generated />
// JSON shape: ASP.NET Core camelCase. No runtime hydration or default values.

export class WireTypes
{
    declare "id": number;
    declare "active": boolean;
    declare "optionalName": string | null;
    /** JSON date/time string; not a JavaScript Date instance. */
    declare "createdAt": string;
    /** JSON TimeSpan string, using the backend's TimeSpan serialization format. */
    declare "duration": string;
    /** JSON number: integers outside JavaScript's safe integer range can lose precision. Use a string-valued API DTO for exact large IDs. */
    declare "largeId": number;
    /** JSON number: JavaScript cannot represent all decimal values exactly. Use a string-valued API DTO when exact decimal precision is required. */
    declare "price": number;
    /** Base64-encoded JSON string (System.Text.Json byte[] representation). */
    declare "blob": string;
    declare "variant": unknown | null;
    declare ["constructor"]: number;
    declare "urlValue": string;
}
